### ISSUE TITLE
About aligning tokens to words

### ISSUE THREAD

**Issue by HAN-oQo** [Jihuai-wpy/SeqXGPT#6]
Hi, Thank you for your awesome projects!

I read your paper recently and now watching your codes.
But I couldn't find which part of your code is related to the following.
Can you kindly indicate the part me please?

> As a result,we align tokens to words, which addresses potential discrepancies in the tokenization process across different LLMs. We use a general word-wise tokenization of S:w=[w1,...,wt] and align calculated log probabilities of tokens in x to the words in w.

**Comment by Jihuai-wpy** [comment]
Thank you very much for your interest in my work. I'm pleased that you noticed this detail. Actually, it's a rather intricate alignment process. The specific code is in the SeqXGPT/SeqXGPT/backend_utils.py file. 

Since different tokenizers segment text in various ways, for each type of tokenizer, we have implemented a specific class to align tokens with words. Our general approach is that both tokens and words share the same basic smallest units (for example, the smallest unit in BPE is a character, while in BBPE it's a byte). We start by breaking down the tokens into their smallest units, where each smallest unit carries the probability of its token. Then, we combine these to form words, where the probability of a word is the average probability of all the smallest units that make it up.

Of course, there are other implementation methods as well. For example, a simpler alternative method could be to assume that the probability of each word is the probability of the first token that makes up that word, and so on.

I hope my response is helpful to you. If you have more questions in the future, feel free to ask.

**Comment by HAN-oQo** [comment]
Thank you so much for your kind answer!
Now I found the detail in your code. I will try to follow your README. 
Thanks for fast, nice answer again :)
